name: assignment-test
on:
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'
jobs:
    unit-test:
        container:
          image: cuaesd/aesd-autotest:24-assignment1
          options: --network aesd-network  # This tells Docker to use the specified network
        runs-on: self-hosted
        steps:
          - uses: actions/checkout@v2
          - name: Checkout submodules
            run : git submodule update --init --recursive
          - name: Run unit test
            run: ./unit-test.sh
    full-test:
        container:
          image: cuaesd/aesd-autotest:24-assignment1
          options: --network aesd-network  # This tells Docker to use the specified network
        runs-on: self-hosted
        steps:
          - uses: actions/checkout@v2
          - name: Checkout submodules
            run : git submodule update --init --recursive
          - name: Run full test
            run: ./full-test.sh
